# config.yaml

# 오디오 관련 설정
audio:
  frame_size: 480        # 오디오 프레임 크기
  sample_rate: 8000     # 샘플링 레이트 (8kHz)
  frame_duration_ms: 30  # 프레임 길이 (밀리초)

network:
  socket_timeout: 60     # 소켓 타임아웃 시간 (초)
  ip: "127.0.0.1"       # 서버 IP 주소
  port: 5000            # 서버 포트 번호

# Whisper 모델 설정
model:
  size: "small"          # 모델 크기 (tiny, base, small, medium, large-v2)
  device: "cuda"        # 실행 장치 (cpu 또는 cuda)
  language: "ko"        # 인식 언어
  channel: 1            # 동시 처리 채널 수

# VAD(Voice Activity Detection) 설정
vad:
  mode: 1              # VAD 모드 (0-3)

# 로그 설정
logging:
  level : "info"       # 로그 레벨 (critical,error, warn, warning, info, debug)
  save_pcm : True       # pcm 파일 저장 여부
  log_path: "./log/STT_log"  # 로그 저장 경로
  pcm_path: "./data"         # PCM 파일 저장 경로